variables:
- group: uat

name: $(pipelinename)  

stages :        
  - stage: arm_template_deploy
    jobs:
      - job: arm_template_deploy
        steps:
              - checkout: self
 
              - task: AzureResourceManagerTemplateDeployment@3
                inputs:
                  deploymentScope: 'Resource Group'
                  azureResourceManagerConnection: 'service_connection'
                  subscriptionId: '4287af3b-f106-4eae-9bee-6c41866cd5e1'
                  action: 'Create Or Update Resource Group'
                  resourceGroupName: 'sa-uat'
                  location: 'westeurope'
                  templateLocation: 'Linked artifact'
                  csmFile: '$(System.DefaultWorkingDirectory)/arm_storageaccount_uat.json'
                  csmParametersFile: '$(System.DefaultWorkingDirectory)/saccount_parameters_uat.json'